#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# 03_run_son_spectral_proteome.sh
#
# Run son_spectral_final.py on all 2D output folders generated
# from a complete UniProt proteome.
#
# Example:
#   bash 03_run_son_spectral_proteome.sh UP000000556
#
# Input:
#   /protDC/data/work/UP000000556/2D_out.q/
#
# Output:
#   /protDC/data/work/UP000000556/Signals.q/
# ============================================================


# -------------------------
# Proteome ID
# -------------------------

# The first command-line argument is the UniProt proteome ID.
# If no argument is given, UP000000556 is used as the default example.
PROTEOME_ID="${1:-UP000000556}"


# -------------------------
# Editable paths
# -------------------------

# Edit this variable to point to the location where son_spectral_final.py is stored.
SON="/protDC/Scripts/son_spectral_final.py"

# Optional: edit this variable if a Python virtual environment must be activated.
#
# Leave it empty if no environment activation is needed:
#   VENV_ACT=""
#
# Example for a normal Python venv:
#   VENV_ACT="/protDC/venv/bin/activate"
#
# Example for a specific Conda environment by path:
#   VENV_ACT="/protDC/miniconda3/envs/protDC/bin/activate"
VENV_ACT=""

# Edit this variable to the main working folder.
WORK_ROOT="/protDC/data/work"

# This folder should contain the output generated by make_2d.py.
TWO_D_ROOT="${WORK_ROOT%/}/${PROTEOME_ID}/2D_out.q"

# Output folder for son_spectral_final.py.
OUT_FOLDER="${WORK_ROOT%/}/${PROTEOME_ID}/Signals.q"

# Number of jobs used by son_spectral_final.py.
# Use 1 when memory is a concern.
JOBS=1

# -------------------------
# Activate Python environment, if needed
# -------------------------

activate_python_env() {
    if [[ -z "$VENV_ACT" ]]; then
        echo "No Python environment specified. Continuing without environment activation."
        return 0
    fi

    if [[ ! -f "$VENV_ACT" ]]; then
        echo "Error: Python environment activation script not found: $VENV_ACT" >&2
        exit 1
    fi

    # This function is called with no arguments, so the proteome ID passed to
    # the main script is not visible as $1 inside the sourced activation script.
    # shellcheck disable=SC1090
    source "$VENV_ACT"
}

activate_python_env


# -------------------------
# Basic checks
# -------------------------

if [[ ! -f "$SON" ]]; then
    echo "Error: son_spectral_final.py was not found: $SON" >&2
    exit 1
fi

if [[ ! -d "$TWO_D_ROOT" ]]; then
    echo "Error: 2D output folder was not found: $TWO_D_ROOT" >&2
    echo "Please run 02_run_make_2d_proteome.sh first." >&2
    exit 1
fi

if ! command -v python >/dev/null 2>&1; then
    echo "Error: python was not found in PATH." >&2
    echo "Please activate the correct Python environment or set VENV_ACT." >&2
    exit 1
fi

mkdir -p "$OUT_FOLDER"


# -------------------------
# Collect 2D input folders
# -------------------------

# make_2d.py often creates one subfolder per query protein under 2D_out.q.
# For proteome-level input, we process all immediate subfolders.
# If no subfolders exist, we fall back to using TWO_D_ROOT itself.

TMP_INPUT_LIST=$(mktemp)
trap 'rm -f "$TMP_INPUT_LIST"' EXIT

find "$TWO_D_ROOT" -mindepth 1 -maxdepth 1 -type d | sort > "$TMP_INPUT_LIST"

if [[ ! -s "$TMP_INPUT_LIST" ]]; then
    printf '%s\n' "$TWO_D_ROOT" > "$TMP_INPUT_LIST"
fi

input_count=$(wc -l < "$TMP_INPUT_LIST" | tr -d ' ')

echo "Proteome ID: $PROTEOME_ID"
echo "2D root folder: $TWO_D_ROOT"
echo "Number of 2D input folders to process: $input_count"
echo "Signal output folder: $OUT_FOLDER"


# -------------------------
# Run son_spectral_final.py
# -------------------------

while IFS= read -r two_d_input; do
    [[ -n "$two_d_input" ]] || continue

    query_name=$(basename "$two_d_input")

    echo
    echo "Running son_spectral_final.py:"
    echo "  Query/2D folder : $query_name"
    echo "  Input           : $two_d_input"
    echo "  Output          : $OUT_FOLDER"
    echo "  Jobs            : $JOBS"

    python "$SON" \
        --o "$OUT_FOLDER" \
        -j "$JOBS" \
        "$two_d_input"

done < "$TMP_INPUT_LIST"


echo
echo "son_spectral_final.py finished successfully."
echo "Signal files are in: $OUT_FOLDER"
