#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# 05_run_topn_T_against_query_proteome.sh
#
# Purpose:
#   Run topn using the Pro_T FASTA chunks generated by script 04
#   as query files:
#        T1, T2, T3, ...
#
#   Use the original query proteome FASTA as the target:
#        $WORK_ROOT/$PROTEOME_ID/$PROTEOME_ID.accession.fasta
#
# Output:
#        $WORK_ROOT/$PROTEOME_ID/topN_out.t
#
# Example:
#   bash 05_run_topn_T_against_query_proteome.sh UP000000556
#
# Important:
#   The T FASTA chunks will be named T1, T2, T3, ...
# ============================================================


# -------------------------
# Proteome ID
# -------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"

PROTEOME_ID="${1:-UP000000556}"


# -------------------------
# Editable variables
# -------------------------

# Override TOPN to use a custom topn executable.
TOPN="${TOPN:-${TOOLS_DIR}/bin/topn}"

# N is the number of homolog candidates selected by topn.
# Suggested values:
#   N=20 for bacteria
#   N=50 for eukaryotes
N=20

# Edit this variable to the main working folder.
WORK_ROOT="/protDC/data/work"


# -------------------------
# Derived paths
# -------------------------

WORK_DIR="${WORK_ROOT%/}/${PROTEOME_ID}"
T_FASTA_DIR="${WORK_DIR}/Pro_T_FASTA"
TARGET_FASTA="${WORK_DIR}/${PROTEOME_ID}.accession.fasta"
OUT_FOLDER="${WORK_DIR}/topN_out.t"
LIST_DIR="${WORK_DIR}/lists"
QUERY_LIST="${LIST_DIR}/T_query_files.list"


# -------------------------
# Basic checks
# -------------------------

if [[ ! -x "$TOPN" ]]; then
    echo "Error: topn is not executable or was not found: $TOPN" >&2
    exit 1
fi

if [[ ! -d "$T_FASTA_DIR" ]]; then
    echo "Error: Pro_T FASTA folder was not found: $T_FASTA_DIR" >&2
    echo "Please run script 04 first." >&2
    exit 1
fi

if [[ ! -s "$TARGET_FASTA" ]]; then
    echo "Error: original proteome FASTA was not found: $TARGET_FASTA" >&2
    echo "Please run script 01 first." >&2
    exit 1
fi

mkdir -p "$OUT_FOLDER" "$LIST_DIR"


# -------------------------
# Collect T FASTA query chunks
# -------------------------

# T[0-9]* matches T1, T2, T10, etc.
find "$T_FASTA_DIR" -mindepth 1 -maxdepth 1 -type f -name 'T[0-9]*' | sort -V > "$QUERY_LIST"

query_count=$(wc -l < "$QUERY_LIST" | tr -d ' ')

if [[ "$query_count" -eq 0 ]]; then
    echo "Error: no T[0-9]* query FASTA files were found in $T_FASTA_DIR" >&2
    echo "Expected files like: T1, T2, T3, ..." >&2
    exit 1
fi

echo "Proteome ID: $PROTEOME_ID"
echo "T FASTA folder: $T_FASTA_DIR"
echo "Target FASTA: $TARGET_FASTA"
echo "topN output folder: $OUT_FOLDER"
echo "T query list: $QUERY_LIST"
echo "Number of T query chunks: $query_count"
echo "topn -n value: $N"


# -------------------------
# Run topn
# -------------------------

while IFS= read -r query_fasta; do
    [[ -n "$query_fasta" ]] || continue

    query_name=$(basename "$query_fasta")

    if ! grep -q '^>' "$query_fasta"; then
        echo "Warning: skipping empty FASTA chunk without records: $query_fasta" >&2
        continue
    fi

    output="${OUT_FOLDER%/}/${query_name}_${PROTEOME_ID}"

    echo
    echo "Running topn:"
    echo "  Query chunk  : $query_name"
    echo "  Query FASTA  : $query_fasta"
    echo "  Target FASTA : $TARGET_FASTA"
    echo "  Output       : $output"
    echo "  N            : $N"

    "$TOPN" \
        -q "$query_fasta" \
        -t "$TARGET_FASTA" \
        -o "$output" \
        -n "$N"

done < "$QUERY_LIST"


echo
echo "Script 05 finished."
echo "topN output folder: $OUT_FOLDER"
