#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# 06_run_make_2d_T.sh
#
# Purpose:
#   Run make_2d.py on the topN output generated by script 05.
#
# Input:
#        $WORK_ROOT/$PROTEOME_ID/topN_out.t
#
# Output:
#        $WORK_ROOT/$PROTEOME_ID/2D_out.t
#
# Example:
#   bash 06_run_make_2d_T.sh UP000000556
#
# Important:
#   topN_out.t should contain topN result files such as:
#        T1_UP000000556
#        T2_UP000000556
#        T3_UP000000556
# ============================================================


# -------------------------
# Proteome ID
# -------------------------

PROTEOME_ID="${1:-UP000000556}"


# -------------------------
# Editable variables
# -------------------------

# Edit this variable to point to the location where make_2d.py is stored.
MAKE_2D="/protDC/Scripts/make_2d.py"

# N is the number of homolog candidates selected from each target proteome.
# Suggested values:
#   N=20 for bacteria
#   N=50 for eukaryotes
N=20

# Optional Python environment activation.
# Leave VENV_ACT empty if no Python environment needs to be activated.
# Examples:
#   VENV_ACT="/protDC/venv/bin/activate"
#   VENV_ACT="/protDC/miniconda3/envs/protDC/bin/activate"
VENV_ACT=""

# Edit this variable to the main working folder.
WORK_ROOT="/protDC/data/work"


# -------------------------
# Derived paths
# -------------------------

WORK_DIR="${WORK_ROOT%/}/${PROTEOME_ID}"
TOPN_OUT="${WORK_DIR}/topN_out.t"
OUT_FOLDER="${WORK_DIR}/2D_out.t"


# -------------------------
# Functions
# -------------------------

activate_python_env() {
    if [[ -z "$VENV_ACT" ]]; then
        echo "No Python environment specified. Continuing without environment activation."
        return 0
    fi

    if [[ ! -f "$VENV_ACT" ]]; then
        echo "Error: Python environment activation script not found: $VENV_ACT" >&2
        exit 1
    fi

    # This function is called with no arguments, so the proteome ID passed to
    # the main script is not visible as $1 inside the sourced activation script.
    # shellcheck disable=SC1090
    source "$VENV_ACT"
}


# -------------------------
# Basic checks
# -------------------------

if [[ ! -f "$MAKE_2D" ]]; then
    echo "Error: make_2d.py was not found: $MAKE_2D" >&2
    exit 1
fi

if [[ ! -d "$TOPN_OUT" ]]; then
    echo "Error: topN output folder was not found: $TOPN_OUT" >&2
    echo "Please run script 05 first." >&2
    exit 1
fi

valid_count=$(find "$TOPN_OUT" -mindepth 1 -maxdepth 1 -type f -name "T[0-9]*_${PROTEOME_ID}" | wc -l | tr -d ' ')

if [[ "$valid_count" -eq 0 ]]; then
    echo "Error: no valid topN output files were found in $TOPN_OUT" >&2
    echo "Expected files like: T1_${PROTEOME_ID}, T2_${PROTEOME_ID}, ..." >&2
    exit 1
fi

mkdir -p "$OUT_FOLDER"


# -------------------------
# Activate Python environment, if needed
# -------------------------

activate_python_env

if ! command -v python >/dev/null 2>&1; then
    echo "Error: python was not found in PATH." >&2
    echo "Please activate the correct Python environment or set VENV_ACT." >&2
    exit 1
fi


# -------------------------
# Run make_2d.py
# -------------------------

echo
echo "Running make_2d.py:"
echo "  Proteome ID    : $PROTEOME_ID"
echo "  Input folder   : $TOPN_OUT"
echo "  Output folder  : $OUT_FOLDER"
echo "  N              : $N"
echo "  Valid files    : $valid_count"

python "$MAKE_2D" \
    --o "$OUT_FOLDER" \
    -n "$N" \
    "$TOPN_OUT"


echo
echo "Script 06 finished."
echo "2D output folder: $OUT_FOLDER"
