#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# 6.1_leiden_01_preprocess.sh
#
# Purpose:
#   Run leiden_01_preprocess.py on the SJI network generated by
#   script 05.
#
# Input:
#   $WORK_ROOT/SJI_network/all_proteomes.sji.network.csv
#
# Outputs:
#   $WORK_ROOT/Leiden/integer_edges.csv
#   $WORK_ROOT/Leiden/protein_id_mapping.csv
#
# Example:
#   bash 6.1_leiden_01_preprocess.sh
# ============================================================

LEIDEN_01="/protDC/Scripts/leiden_01_preprocess.py"

VENV_ACT=""

WORK_ROOT="/protDC/data/work/all_proteomes"

INPUT_HAS_HEADER=false
CHUNKSIZE=5000000

NETWORK_CSV="${WORK_ROOT%/}/SJI_network/all_proteomes.sji.network.csv"
LEIDEN_ROOT="${WORK_ROOT%/}/Leiden"
INTEGER_EDGES="${LEIDEN_ROOT}/integer_edges.csv"
MAPPING_CSV="${LEIDEN_ROOT}/protein_id_mapping.csv"

activate_python_env() {
    if [[ -z "$VENV_ACT" ]]; then
        echo "No Python environment specified. Continuing without environment activation."
        return 0
    fi

    if [[ ! -f "$VENV_ACT" ]]; then
        echo "Error: Python environment activation script not found: $VENV_ACT" >&2
        exit 1
    fi

    # This function is called with no arguments, so command-line parameters
    # passed to the main script are not visible as $1 inside the sourced
    # activation script.
    # shellcheck disable=SC1090
    source "$VENV_ACT"
}

if [[ ! -f "$LEIDEN_01" ]]; then
    echo "Error: leiden_01_preprocess.py was not found: $LEIDEN_01" >&2
    exit 1
fi

if [[ ! -s "$NETWORK_CSV" ]]; then
    echo "Error: input SJI network was not found or is empty: $NETWORK_CSV" >&2
    echo "Please run script 05 first." >&2
    exit 1
fi

mkdir -p "$LEIDEN_ROOT"

activate_python_env

if ! command -v python >/dev/null 2>&1; then
    echo "Error: python was not found in PATH." >&2
    echo "Please activate the correct Python environment or set VENV_ACT." >&2
    exit 1
fi

cd "$LEIDEN_ROOT"

cmd=(
    python "$LEIDEN_01"
    --input "$NETWORK_CSV"
    --out_edges "$INTEGER_EDGES"
    --out_mapping "$MAPPING_CSV"
    --chunksize "$CHUNKSIZE"
)

if [[ "$INPUT_HAS_HEADER" == true ]]; then
    cmd+=(--has_header)
fi

echo "Running Leiden preprocessing:"
echo "  Script        : $LEIDEN_01"
echo "  Input network : $NETWORK_CSV"
echo "  Integer edges : $INTEGER_EDGES"
echo "  Mapping CSV   : $MAPPING_CSV"
echo "  Input header  : $INPUT_HAS_HEADER"
echo "  Chunksize     : $CHUNKSIZE"

"${cmd[@]}"

if [[ ! -s "$INTEGER_EDGES" ]]; then
    echo "Error: integer edge file was not created or is empty: $INTEGER_EDGES" >&2
    exit 1
fi

if [[ ! -s "$MAPPING_CSV" ]]; then
    echo "Error: protein ID mapping was not created or is empty: $MAPPING_CSV" >&2
    exit 1
fi

echo
echo "Script 6.1 finished."
echo "Integer edge file: $INTEGER_EDGES"
echo "Protein mapping  : $MAPPING_CSV"
