#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# 09_run_preprocess_graph.sh
#
# Purpose:
#   Run preprocess_graph.py on the SJI network generated by script 05.
#
# Input:
#   $WORK_ROOT/SJI_network/all_proteomes.sji.network.csv
#
# Outputs:
#   $WORK_ROOT/graph_index/<GRAPH_PREFIX>.node_ids.tsv
#   $WORK_ROOT/graph_index/<GRAPH_PREFIX>.adj.bin
#   $WORK_ROOT/graph_index/<GRAPH_PREFIX>.adj.index.bin
#
# Example:
#   bash 09_run_preprocess_graph.sh
#
# Notes:
#   preprocess_graph.py reads a 3-column edge list:
#       NodeA,NodeB,Weight
#
#   By default, it assumes the input edge file has NO header.
#   Set INPUT_HAS_HEADER=true if your edge file has a header row.
# ============================================================


# -------------------------
# Editable variables
# -------------------------

# Edit this variable to point to preprocess_graph.py.
PREPROCESS_GRAPH="/protDC/Scripts/preprocess_graph.py"

# Optional Python environment activation.
# Leave VENV_ACT empty if no Python environment needs to be activated.
# Examples:
#   VENV_ACT="/protDC/venv/bin/activate"
#   VENV_ACT="/protDC/miniconda3/envs/protDC/bin/activate"
VENV_ACT=""

# Edit this variable to the main working folder used in scripts 01-08.
WORK_ROOT="/protDC/data/work/all_proteomes"

# Three-letter prefix for output graph-index files.
#
# Output files will be:
#   <GRAPH_PREFIX>.node_ids.tsv
#   <GRAPH_PREFIX>.adj.bin
#   <GRAPH_PREFIX>.adj.index.bin
#
# Examples:
#   GRAPH_PREFIX="all"
#   GRAPH_PREFIX="bac"
#   GRAPH_PREFIX="euk"
GRAPH_PREFIX="all"

# Set true only if all_proteomes.sji.network.csv has a header row.
# The project edge files are usually headerless, so the default is false.
INPUT_HAS_HEADER=false

# Optional per-node top-K filtering by edge weight.
#
# Leave empty to keep all neighbors:
#   TOP_K=""
#
# Example:
#   TOP_K=100
TOP_K=""


# -------------------------
# Derived paths
# -------------------------

NETWORK_CSV="${WORK_ROOT%/}/SJI_network/all_proteomes.sji.network.csv"
OUT_DIR="${WORK_ROOT%/}/graph_index"
OUTPUT_PREFIX="${OUT_DIR}/${GRAPH_PREFIX}"

NODE_IDS_OUT="${OUTPUT_PREFIX}.node_ids.tsv"
ADJ_OUT="${OUTPUT_PREFIX}.adj.bin"
ADJ_INDEX_OUT="${OUTPUT_PREFIX}.adj.index.bin"


# -------------------------
# Functions
# -------------------------

activate_python_env() {
    if [[ -z "$VENV_ACT" ]]; then
        echo "No Python environment specified. Continuing without environment activation."
        return 0
    fi

    if [[ ! -f "$VENV_ACT" ]]; then
        echo "Error: Python environment activation script not found: $VENV_ACT" >&2
        exit 1
    fi

    # This function is called with no arguments, so command-line parameters
    # passed to the main script are not visible as $1 inside the sourced
    # activation script.
    # shellcheck disable=SC1090
    source "$VENV_ACT"
}

validate_prefix_in_bash() {
    local prefix="$1"

    if [[ -z "$prefix" ]]; then
        echo "Error: GRAPH_PREFIX cannot be empty." >&2
        exit 1
    fi

    if [[ ! "$prefix" =~ ^[A-Za-z0-9]{1,3}$ ]]; then
        echo "Error: GRAPH_PREFIX must be 1-3 letters/numbers with no punctuation." >&2
        echo "Current value: $prefix" >&2
        exit 1
    fi
}


# -------------------------
# Basic checks
# -------------------------

validate_prefix_in_bash "$GRAPH_PREFIX"

if [[ ! -f "$PREPROCESS_GRAPH" ]]; then
    echo "Error: preprocess_graph.py was not found: $PREPROCESS_GRAPH" >&2
    exit 1
fi

if [[ ! -s "$NETWORK_CSV" ]]; then
    echo "Error: SJI network file was not found or is empty: $NETWORK_CSV" >&2
    echo "Please run script 05 first." >&2
    exit 1
fi

if [[ -n "$TOP_K" && ! "$TOP_K" =~ ^[0-9]+$ ]]; then
    echo "Error: TOP_K must be empty or a positive integer. Current value: $TOP_K" >&2
    exit 1
fi

mkdir -p "$OUT_DIR"


# -------------------------
# Activate Python environment, if needed
# -------------------------

activate_python_env

if ! command -v python >/dev/null 2>&1; then
    echo "Error: python was not found in PATH." >&2
    echo "Please activate the correct Python environment or set VENV_ACT." >&2
    exit 1
fi


# -------------------------
# Run preprocess_graph.py
# -------------------------

cmd=(
    python "$PREPROCESS_GRAPH"
    "$NETWORK_CSV"
    --output_prefix "$OUTPUT_PREFIX"
)

if [[ "$INPUT_HAS_HEADER" == true ]]; then
    cmd+=(--has-header)
fi

if [[ -n "$TOP_K" ]]; then
    cmd+=(--top_k "$TOP_K")
fi

echo "Running preprocess_graph.py:"
echo "  Script          : $PREPROCESS_GRAPH"
echo "  Input network   : $NETWORK_CSV"
echo "  Output prefix   : $OUTPUT_PREFIX"
echo "  Input has header: $INPUT_HAS_HEADER"
echo "  TOP_K           : ${TOP_K:-not set}"

"${cmd[@]}"

if [[ ! -s "$NODE_IDS_OUT" ]]; then
    echo "Error: node ID output was not created or is empty: $NODE_IDS_OUT" >&2
    exit 1
fi

if [[ ! -s "$ADJ_OUT" ]]; then
    echo "Error: adjacency binary output was not created or is empty: $ADJ_OUT" >&2
    exit 1
fi

if [[ ! -s "$ADJ_INDEX_OUT" ]]; then
    echo "Error: adjacency index output was not created or is empty: $ADJ_INDEX_OUT" >&2
    exit 1
fi

echo
echo "Script 09 finished."
echo "Node IDs      : $NODE_IDS_OUT"
echo "Adjacency     : $ADJ_OUT"
echo "Adjacency idx : $ADJ_INDEX_OUT"
