#!/usr/bin/env bash
set -euo pipefail

# Edit this variable to point to the location where make_2d.py is stored.
MAKE_2D="/protDC/Scripts/make_2d.py"

# N is the number of homolog candidates selected from each proteome.
# Suggested values: N=50 for eukaryotes and N=20 for bacteria.
N=20

# Optional: edit this variable if a Conda, venv, or other Python environment must be activated.
ENV_ACT="/protDC/miniconda3/bin/activate"

# Edit this variable to the folder containing the output files generated by topN.
# This folder will be used as the input for make_2d.py.
TOPN_OUT="/protDC/data/work/test/topN_out"

# Edit this variable to the output folder for make_2d.py.
OUT_FOLDER="/protDC/data/work/test/2D_out/"

# -------------------------
# Basic checks
# -------------------------

if [[ ! -f "$MAKE_2D" ]]; then
    echo "Error: make_2d.py was not found: $MAKE_2D" >&2
    exit 1
fi

if [[ ! -d "$TOPN_OUT" ]]; then
    echo "Error: topN output folder was not found: $TOPN_OUT" >&2
    exit 1
fi

mkdir -p "$OUT_FOLDER"

# -------------------------
# Activate Python environment, if needed
# -------------------------

# This step is only needed if the required Python environment must be activated.
# If no environment activation is needed, comment out the following block.
if [[ -f "$ENV_ACT" ]]; then
    source "$ENV_ACT"
else
    echo "Warning: environment activation script not found: $ENV_ACT" >&2
    echo "Continuing without activating a Python environment." >&2
fi

# -------------------------
# Run make_2d.py
# -------------------------

python "$MAKE_2D" \
    --o "$OUT_FOLDER" \
    -n "$N" \
    "$TOPN_OUT"

echo "make_2d.py finished successfully."
