#!/usr/bin/env bash
set -euo pipefail

# Edit this variable to point to the location where son_spectral_final.py is stored.
SON="/protDC/Scripts/son_spectral_final.py"

# Optional: edit this variable if a Conda, venv, or other Python environment must be activated.
ENV_ACT="/protDC/miniconda3/bin/activate"

# Edit this variable to the output subfolder generated by make_2d.py.
# This folder will be used as the input for son_spectral_final.py.
#
# Note: make_2d.py can process an input folder containing multiple queries.
# For each query, it creates a separate subfolder under the main 2D_out directory.
# Therefore, this variable should point to the correct query-specific subfolder.
TWO_D_OUT="/protDC/data/work/test/2D_out/query"

# Edit this variable to the output folder for son_spectral_final.py.
OUT_FOLDER="/protDC/data/work/test/Signals/"

# -------------------------
# Basic checks
# -------------------------

if [[ ! -f "$SON" ]]; then
    echo "Error: son_spectral_final.py was not found: $SON" >&2
    exit 1
fi

if [[ ! -d "$TWO_D_OUT" ]]; then
    echo "Error: 2D output folder was not found: $TWO_D_OUT" >&2
    exit 1
fi

mkdir -p "$OUT_FOLDER"

# -------------------------
# Activate Python environment, if needed
# -------------------------

# This step is only required if the appropriate Python environment must be activated.
# If no environment activation is needed, comment out the following block.
if [[ -f "$ENV_ACT" ]]; then
    source "$ENV_ACT"
else
    echo "Warning: environment activation script not found: $ENV_ACT" >&2
    echo "Continuing without activating a Python environment." >&2
fi

# -------------------------
# Run son_spectral_final.py
# -------------------------

# -j 1 is recommended when memory is a concern.
# Otherwise, -j 1 can be removed, and son_spectral_final.py will use all CPUs
# available on the same node. However, if memory is limited, using all CPUs may
# actually slow down the process.
python "$SON" \
    --o "$OUT_FOLDER" \
    -j 1 \
    "$TWO_D_OUT"

echo "son_spectral_final.py finished successfully."
