#!/usr/bin/env bash
set -euo pipefail

# Edit this variable to point to the location where build_network_oneway.py is stored.
SJI_NET="/protDC/Scripts/build_network_oneway.py"

# Optional: edit this variable if a Conda, venv, or other Python environment must be activated.
ENV_ACT="/protDC/miniconda3/bin/activate"

# Edit this variable to the folder containing the signal files generated by son_spectral_final.py.
# This folder will be used as the query input for build_network_oneway.py.
QUERY_DIR="/protDC/data/work/test/Signals/"

# Edit this variable to the protein signal database folder downloaded from the protDC package.
# This folder contains the signal files for all proteins included in the protDC package.
SIGNAL_DIR="/protDC/data/Signal_DB/"

# Edit this variable to the output folder for build_network_oneway.py.
OUT_DIR="/protDC/data/work/test/SJI/"

# Each query protein will have a corresponding .csv file under $OUT_DIR. Review the generated .csv
# files and identify the closest neighbors for each query protein that are already present in the 
# ProtDC system. Use the selected neighbors as input for /tools/runtime/extract_subnetwork.py to extract
# a subnetwork containing those neighbors.

# Then, merge the generated .csv files with the extracted subnetwork .csv file. This can be done 
# with a simple cat command to combine the files. Save the combined .csv file to /data/networks/.

# As the final step, load the combined network, highlight your query proteins, and inspect their 
# local network features.


# -------------------------
# Basic checks
# -------------------------

if [[ ! -f "$SJI_NET" ]]; then
    echo "Error: build_network_oneway.py was not found: $SJI_NET" >&2
    exit 1
fi

if [[ ! -d "$QUERY_DIR" ]]; then
    echo "Error: query signal folder was not found: $QUERY_DIR" >&2
    exit 1
fi

if [[ ! -d "$SIGNAL_DIR" ]]; then
    echo "Error: protein signal database folder was not found: $SIGNAL_DIR" >&2
    exit 1
fi

mkdir -p "$OUT_DIR"

# -------------------------
# Activate Python environment, if needed
# -------------------------

# This step is only required if the appropriate Python environment must be activated.
# If no environment activation is needed, comment out the following block.
if [[ -f "$ENV_ACT" ]]; then
    source "$ENV_ACT"
else
    echo "Warning: environment activation script not found: $ENV_ACT" >&2
    echo "Continuing without activating a Python environment." >&2
fi

# -------------------------
# Run build_network_oneway.py
# -------------------------

python "$SJI_NET" \
    --query "$QUERY_DIR" \
    --db "$SIGNAL_DIR" \
    --output "$OUT_DIR"

echo "build_network_oneway.py finished successfully."
